package project;


import project.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import project.DBConnector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pranavan
 */
public class Function_Checker extends javax.swing.JFrame {

    /**
     * Creates new form Holiday_Checker
     */
    public Function_Checker() {
        initComponents();
        setLocationRelativeTo(null);
    }

     Date date;
    DBConnector db = new DBConnector();
    Connection conn = db.getConnection();
    
    public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
    if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("lsms1?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        holidayQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery.getResultList();
        holidayQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery1.getResultList();
        holidayQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery2.getResultList();
        holidayQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery3.getResultList();
        holidayQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery4.getResultList();
        holidayQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery5.getResultList();
        holidayQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery6.getResultList();
        holidayQuery7 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery7.getResultList();
        holidayQuery8 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT h FROM Holiday h");
        holidayList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : holidayQuery8.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check date");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Functions/Events Checker");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select Date");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Check Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Status");

        Status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Status.setForeground(new java.awt.Color(204, 0, 0));
        Status.setText("Status");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, holidayList6, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${note}"));
        columnBinding.setColumnName("Function/Event name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        scrollPane1.add(jScrollPane1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel2)
                            .addGap(32, 32, 32)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(Status)))))
                .addGap(56, 56, 56)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(84, 84, 84)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Status))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(263, 263, 263))))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         date = jDateChooser1.getDate();
         String status;
         String time;
         String note;
         try {
            java.sql.Date sqlDate = convertUtilDateToSqlDate(date);
            ResultSet rs = conn.createStatement().executeQuery("select * from holiday where date ='" + sqlDate + "' ");
            if(rs.next()) {   
                time=rs.getString("time");
                jLabel4.setText(time);
                
                 status = rs.getString("note");
                 Status.setText(status);
                
             
                
                
            }else{
                Status.setText("N/A");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Function_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Function_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Function_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Function_Checker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Function_Checker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<project.Holiday> holidayList;
    private java.util.List<project.Holiday> holidayList1;
    private java.util.List<project.Holiday> holidayList2;
    private java.util.List<project.Holiday> holidayList3;
    private java.util.List<project.Holiday> holidayList4;
    private java.util.List<project.Holiday> holidayList5;
    private java.util.List<project.Holiday> holidayList6;
    private java.util.List<project.Holiday> holidayList7;
    private java.util.List<project.Holiday> holidayList8;
    private javax.persistence.Query holidayQuery;
    private javax.persistence.Query holidayQuery1;
    private javax.persistence.Query holidayQuery2;
    private javax.persistence.Query holidayQuery3;
    private javax.persistence.Query holidayQuery4;
    private javax.persistence.Query holidayQuery5;
    private javax.persistence.Query holidayQuery6;
    private javax.persistence.Query holidayQuery7;
    private javax.persistence.Query holidayQuery8;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.ScrollPane scrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
